stages:
  - deploy page

pages:
  image: node:16.15.0
  stage: deploy page
  script:
    - yarn
    - yarn build
    - yarn export
    - rm -r ./public
    - mkdir public
    - cp -a ./out/. ./public/
  artifacts:
    paths:
      - public
  when: manual
  environment: production

azure-static-web-apps:
  stage: deploy page
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  variables:
    API_TOKEN: $AZURE_DEPLOYMENT_TOKEN
    APP_PATH: '$CI_PROJECT_DIR/.next'
  when: manual
  script:
    - yarn
    - yarn build
    - echo "App deployed successfully."