stages:
  - deploy page


pages:
  image: node:16.15.0
  stage: deploy page
  script:
    - yarn
    - yarn build
    - yarn export
    - rm -r /public
    - cp -a /out/. /public/
  artifacts:
    paths:
      - public
  when: manual
  environment: production